- plugin_loader.py
- plugins/README.md
- plugins/__init__.py
- plugins/colorcompare.py
- plugins/eightball.py
- plugins/help.py
- plugins/kill.py
- plugins/learnsets.py
- plugins/links.py
- plugins/locations.py
- plugins/misc.py
- plugins/profile.py
- plugins/shitpost.py
- plugins/token.py
- plugins/tours.py
- plugins/translations.py
- plugins/uptime.py
- plugins/usernames.py
Ho fatto uno squash dei singoli commit che modificavano i vari plugin, così invece di eliminare e reinserire i files (orribile) si possono direttamente confrontare i cambiamenti con la precedente implementazione del plugin system. Il downside è che il commit è abbastanza grande, ma penso sia più corretta questa scelta.
Il secondo commit è costituito da cambiamenti del tutto marginali: modifiche ai parametri passati ai decoratori di alcuni plugin e riordinamento delle istruzioni di import nei vari files dei plugin. Non mi sembrava necessario spezzarlo ulteriormente in commit ancora più piccoli.
> Major plugin system refactoring

- plugins/usernames.py
> updated usernomi

- databases/veekun.py
- plugins/guessthemon.py
Also add `PokemonSpeciesFlavorText` veekun table: variable names are consistent with its CSV.
> Add Guess the Mon plugin

- plugins/usernames.py
> add new fundamental command to usernames plugin

- connection.py
- handlers/formats.py
- plugins/tours.py
> let ultrasuca create a random random tour

- plugins/tours.py
> add helpstr to randtour

- plugins/misc.py
[21:49:10] @ULTRASUCA: .randomuser
[21:49:10] *cerbottana: ULTRASUCA
[21:49:15] @ULTRASUCA: .randomuser
[21:49:15] *cerbottana: Francy~y
[21:49:31] @ULTRASUCA: grande francyy
[21:51:22] #Milak: .randomcaio
[21:51:31] #Milak: voglio il comando .randomcaio
> make milak happy

- README.md
- plugins/README.md
> Improve docs

- plugins/tours.py
i heard you like random so i put more random in your random so you can random while you random
> increase randomness in randtour

- plugins/usernames.py
> enjoy ur italian joke punishment room

- plugins/tcg.py
- requirements-dev.txt
- requirements.in
- requirements.txt
- templates/commands/mtg_card.html
Please don't squash.
This feature requires the additional `aiohttp` dependency. The creation of `ClientSession` instances could be optimized but it's outside the scope of this PR.
> Add MtG command

- .github/workflows/main.yml
- README.md
- mypy.ini
- requirements-dev.in
- requirements-dev.txt
- tests/test_placeholder.py
As of title. This is the same setup we used for the experimental points plugin (see 1509ec7e69c3edd9ec20d42d8826bb0cb93b2279). Although the original plugin needs to be refactored, the pytest implementation itself was left unchanged by the models rewrite.
Changelog:
- Add `pytest` dependency to dev requirements.
- Setup bare structure for the `tests/` folder.
- Update `mypy` configuration.
- Update GitHub worflow to perform unit tests.
- Mention tests in `README.md`.
Future simplified folder structure:
```
.
├── LICENSE
├── plugins/
│   ├── __init__.py
│   └── tcg.py
└── tests/
├── conftest.py (not needed yet)
├── fixtures/
│   ├── api/
│   │   └── scryfall/
│   └── websocket/
│       └── tournament/
│           └── end/
├── __init__.py
└── plugins/
├── __init__.py
└── test_tcg.py
``` …
> Add support for unit tests via pytest

- plugins/profile.py
(Il primo commit chiude un issue.)
> Setprofile: Skip validation for authorized users

- plugins/repeats.py
Order of `WHITELIST_CMD` commands is alphabetical but aliases are grouped together.
> Repeats: Filter repeatable commands

- connection.py
- handlers/modchat.py
- handlers/room.py
- models/room.py
- plugins/guessthemon.py
I really dislike the new check added to `Connection._parse_message` but it's probably acceptable as a temporary solution.
> Guessthemon: Add multilang support

- plugins/profile.py
This does interact and reply even if there's no description. Should it?
If so, this closes #109.
> Add clearprofile command

- plugins/quotes.py
> Quotes: Allow restricting randquotes with a keyword

- databases/veekun.py
- tasks/veekun.py
> Rebuild veekun database only when needed

- tests/conftest.py
- tests/handlers/test_modchat.py
- tests/handlers/test_room.py
And check sent messages in /tests/handlers/test_room.py
> Websocket tests: save sent messages to be able to check them when needed

- tests/plugins/test_quotes.py
Adds new tests for the quote parser to check that usernames are colorized correctly.
> Quotes: Add <username> colorization tests

- plugins/eightball.py
- plugins/quotes.py
- poetry.lock
- pyproject.toml
- utils.py
A new version (0.4?) should be released later today, I'm opening this so I do not forget about it
> Bump sqlalchemy-stubs to 0.4

- plugins/usernames.py
> Usernames: Add mihowk command

- plugins/usernames.py
> Usernames: Add caionamax command

- .github/workflows/main.yml
- .github/workflows/publish-container.yml
- .gitignore
- Containerfile
- cerbottana/__main__.py
- cerbottana/databases/veekun.py
- cerbottana/tasks/veekun.py
- cerbottana/utils.py
- tests/conftest.py
- tests/databases/test_veekun.py
- A new environment variable (`CERBOTTANA_CONFIG_PATH`) is specified in the Containerfile to override the path used for configuration files (by default it's the root of the repository)
- The veekun database rebuilding logic no longer relies on git
> Add OCI container

- README.md
https://github.com/badges/shields/issues/8671
> Readme: fix workflow badge

- .github/workflows/publish-container.yml
Automatic dependency updates serve almost the same purpose
> Remove monthly container rebuilds
